#!/bin/bash
# Jenkins CI Light Server Service script v1.0
# acts as service script for Jenkins CI Light Server
# USAGE: start|stop|status|logs
#

ROOT_DIR=/opt/jenkins-ci-light

case "$1" in
start)
echo "Starting Jenkins CI Light Server."
python $ROOT_DIR/led.py -s --log=DEBUG &
;;
stop)
echo "Stopping Jenkins CI Light server."
PID=$(cat /tmp/jenkins-ci-light.pid 2>/dev/null)
if [ -n "$PID" ]
then
	kill $PID
fi
;;
logs)
echo "Showing jenkins-ci-light logs: $ROOT_DIR/jenkins-ci-light.log"
tail -f $ROOT_DIR/jenkins-ci-light.log
;;
status)
# Check to see if the process is running
ps aux|grep -v grep|grep -i $ROOT_DIR/led.py
;;

*)
echo “Jenkins CI Light Server Service”
echo $”Usage: $0 {start|stop|status|logs}”
exit 1
esac
exit 0
