#!/bin/bash
# Jenkins CI Light Server Service script v1.0
# acts as service script for Jenkins CI Light Server
# USAGE: start|stop|status|logs
#
case "$1" in
start)
echo "Starting Jenkins CI Light Server."
python /usr/local/jenkins-ci-light/led.py -s --log=DEBUG &
;;
stop)
echo "Stopping Jenkins CI Light server."
PID=$(cat /tmp/jenkins-ci-light.pid 2>/dev/null)
if [ -n "$PID" ]
then
	kill $PID
fi
;;
logs)
echo "Showing jenkins-ci-light logs: /usr/local/var/jenkins-ci-light/server.log"
tail -f /usr/local/var/jenkins-ci-light/server.log
;;
status)
# Check to see if the process is running
ps aux|grep -v grep|grep -i /usr/local/jenkins-ci-light/led.py
;;

*)
echo “Jenkins CI Light Server Service”
echo $”Usage: $0 {start|stop|status|logs}”
exit 1
esac
exit 0
